# Generated by Django 4.2.11 on 2024-03-14 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_remove_recipient_id_alter_recipient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmngmt',
            name='id',
        ),
        migrations.AlterField(
            model_name='branchmngmt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='branch', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Recipient', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
