# Generated by Django 4.2.11 on 2024-03-14 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_donation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestdonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('medicine_amount', models.IntegerField(blank=True, null=True)),
                ('cash', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
